language: ruby
rvm:
- 2.3.0

sudo: required

before_deploy:
- gem install mime-types -v 2.6.2

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

